### ISSUE TITLE
[NB-04] 인트로 화면 개발

### ISSUE THREAD

**Issue by boring-km** [boring-km/nkrv_bible#8]
## 구현할 기능

- Lottie 애니메이션을 앱 시작할 때 잠깐 띄우고, 로그인 화면으로 이동
- 로딩 화면에서 최대한 성경이 떠오르도록 하기

## TODO
- 자동 로그인이 활성화 된다면 로딩화면 뒤에서 수행해야함

**Comment by boring-km** [comment]
@navyCK 자동로그인 할 때 인트로화면이랑 연계해야 해요 ㅎ

**Comment by navyCK** [comment]
확인했어요~!
